<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp79.000</name>
   <tag></tag>
   <elementGuidId>730cfada-d246-4785-a297-f6e805f50560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section/div/div[2]/div/div[2]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29296b84-0975-4060-b02e-067c183aa85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>0eb00254-8fb5-4bf5-a9f0-a4971b46e62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp79.000</value>
      <webElementGuid>8e2066a1-d461-4846-8aa6-707ef1de10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/section[@class=&quot;container margin-top-s&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/div[@class=&quot;pdp__content-right&quot;]/div[2]/div[@class=&quot;pdp-action-right container-card pdp__not-hidden&quot;]/div[@class=&quot;price-box&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>be4e94b8-8526-4d44-bc7b-d0787b3f346c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/div[2]/div/div[2]/div/div[2]/span</value>
      <webElementGuid>f89f7c01-ecff-45b0-9359-f2852008e9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::span[2]</value>
      <webElementGuid>f00fc717-57af-4e05-9b21-daaacbfe622a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::span[3]</value>
      <webElementGuid>86c7384d-ae0b-43ad-87ce-f6cd90074a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S&amp;K'])[1]/preceding::span[1]</value>
      <webElementGuid>4f05067a-af33-4f3b-a502-a11d93bc93f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp']/parent::*</value>
      <webElementGuid>cf9d653b-2f4e-4d42-88ae-ca1a576f3a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>77e4e512-af48-4ba4-ab99-59c3bc485575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rp79.000' or . = 'Rp79.000')]</value>
      <webElementGuid>89108e2e-a261-41ab-848e-d5f2ca25ddf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
