<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kategori</name>
   <tag></tag>
   <elementGuidId>b156fe3d-6a30-4d75-a55a-a6e807bce8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerCategory']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.head-space-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03d37818-e006-4d63-bb24-83ca1d16132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>head-space-text</value>
      <webElementGuid>8de71643-dedf-483e-8497-a217de3f63c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>557ef30e-565f-4394-8a7c-1486a1b4aa78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerCategory&quot;)/div[1]/div[@class=&quot;head-space-text&quot;]</value>
      <webElementGuid>8080fe57-a6eb-43ea-a470-d91a46d6777e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerCategory']/div/div</value>
      <webElementGuid>595c0c48-5e1f-4693-9665-85ea444194a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratis Ongkir'])[1]/following::div[7]</value>
      <webElementGuid>41f9b096-4df1-4b82-9d15-c8e94fd02b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer and Earn'])[1]/following::div[7]</value>
      <webElementGuid>cd8dfdac-3103-4b09-9a4f-e8383f706e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspirasi'])[1]/preceding::div[1]</value>
      <webElementGuid>0cd610cc-d65b-4d8b-8c86-357029ff8978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek Pesanan Saya'])[1]/preceding::div[13]</value>
      <webElementGuid>f9c47b7e-c87c-4247-96c4-dd95a8cf59ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kategori']/parent::*</value>
      <webElementGuid>289cf9db-77a7-44a0-9c02-1af1c71f9169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>db143f87-6ac1-49f7-a57a-a8810419ddaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>47895bb5-9b6f-4f32-aeb1-b6ad330f1f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
