<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lihat Produk_image-secondary</name>
   <tag></tag>
   <elementGuidId>27930652-5943-4700-b465-98658ef97f2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='image-secondary'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d61ef050-290c-481c-b6d3-40ac53d683c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shim</value>
      <webElementGuid>c425ad9c-bc5e-4f5f-9f36-7a34a20bec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image-secondary</value>
      <webElementGuid>f61476d3-b7bc-4e39-aa84-3d494dc07c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tanaman Artifisial Grass Bush 70 Cm - Hijau</value>
      <webElementGuid>1e5495cb-dfc8-41fc-8644-fe9b9eb95038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tanaman Artifisial Grass Bush 70 Cm - Hijau</value>
      <webElementGuid>b53ce99c-abf3-4387-b2ca-1f94fc66df17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>170</value>
      <webElementGuid>5b84514f-95fb-4e6a-80c7-20f3392198ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>170</value>
      <webElementGuid>e904cdcd-46ef-483a-8691-4ea56c323ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/ruparupa-com/image/upload/w_300,h_300,f_auto,q_auto/f_auto,q_auto/v1645247523/Products/10458029_2.jpg</value>
      <webElementGuid>d47a3284-06f0-4df1-b100-9813507161bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-category-list&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8 right-content&quot;]/div[@class=&quot;product-container-pcp container-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-3&quot;]/div[@class=&quot;product-container product-container-hovered&quot;]/div[@class=&quot;image-card&quot;]/div[@class=&quot;bitmap&quot;]/div[@class=&quot;item selected&quot;]/span[1]/a[1]/img[@id=&quot;image-secondary&quot;]</value>
      <webElementGuid>6fdffd55-2bb4-4427-903b-14245339a1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='image-secondary'])[3]</value>
      <webElementGuid>f8d66541-5b08-4fa1-9b92-b486fe3cffee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product-category-list']/div/div[2]/div[2]/div/div[3]/div/div/div/div/span/a/img[2]</value>
      <webElementGuid>1eac0490-1345-4f20-9c35-4b18bf37b256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Tanaman Artifisial Grass Bush 70 Cm - Hijau'])[2]</value>
      <webElementGuid>94e404cc-ab1c-4102-927c-bed5223c5387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/a/img[2]</value>
      <webElementGuid>eb2f12ba-ef77-41b2-b95e-e51bc2ca8e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'image-secondary' and @title = 'Tanaman Artifisial Grass Bush 70 Cm - Hijau' and @alt = 'Tanaman Artifisial Grass Bush 70 Cm - Hijau' and @src = 'https://res.cloudinary.com/ruparupa-com/image/upload/w_300,h_300,f_auto,q_auto/f_auto,q_auto/v1645247523/Products/10458029_2.jpg']</value>
      <webElementGuid>498ec0b7-c8fc-49c2-a3cc-ea5b777e0c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
