<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Buy 1 Get 1</name>
   <tag></tag>
   <elementGuidId>fa9d863b-22a3-4df0-9187-96870aa5b039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='label-content-arrow']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b5b5a575-4953-440b-9a87-89af78648a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-text</value>
      <webElementGuid>f1976a30-b6a2-4d82-8fd9-67ea3f167175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>label-Buy_1_Get_1</value>
      <webElementGuid>5dba6877-bc44-4485-aa38-3529148e5c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy 1 Get 1</value>
      <webElementGuid>907192f3-56f8-4e32-84e4-d732788b34d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label-content-arrow&quot;)/div[@class=&quot;checkbox checkbox-primary&quot;]/label[@class=&quot;label-text&quot;]</value>
      <webElementGuid>c36fb701-12e3-4f8e-969c-5d202c334cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='label-content-arrow']/div[2]/label</value>
      <webElementGuid>ef8ae8f0-dd0f-47cb-b33c-cc0146201b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Offer'])[1]/following::label[1]</value>
      <webElementGuid>4f895043-0267-4c05-aa63-5a007772fc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[2]/following::label[2]</value>
      <webElementGuid>1db0df70-013d-4256-9280-9938c09fbe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy 2 Get 1'])[1]/preceding::label[1]</value>
      <webElementGuid>e8648520-a374-4d8f-90ad-7482561d4781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clearance Sale'])[1]/preceding::label[2]</value>
      <webElementGuid>33501bf3-33f9-4af5-84cb-1f83406635d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy 1 Get 1']/parent::*</value>
      <webElementGuid>1ace4ac3-eba9-4288-8d4d-83a9e68dadf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/label</value>
      <webElementGuid>9a71383f-39b9-47fc-b168-659268140337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Buy 1 Get 1' or . = 'Buy 1 Get 1')]</value>
      <webElementGuid>eadf59bf-5638-409a-934a-05a57006084b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
